// Generated by CoffeeScript 1.4.0
(function() {
  var StumpLog, abc, clientlog, colors, decklog, defaults, dummyinspect, extend, fs, genericinspect, glocount, isnode, lfile, merge, obj_for_display, otherlog, serverlog, type_to_string, util, _i, _j, _len, _ref,
    __hasProp = {}.hasOwnProperty,
    _this = this,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice;

  isnode = require('isnode');

  extend = function(object, properties) {
    var key, val;
    for (key in properties) {
      if (!__hasProp.call(properties, key)) continue;
      val = properties[key];
      object[key] = val;
    }
    return object;
  };

  merge = function(options, overrides) {
    return extend(extend({}, options), overrides);
  };

  type_to_string = function(obj) {
    var classToType, myClass, name, _i, _len, _ref;
    if (obj === void 0 || obj === null) {
      return String(obj);
    }
    classToType = new Object;
    _ref = "Boolean Number String Function Array Date RegExp".split(" ");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      classToType["[object " + name + "]"] = name.toLowerCase();
    }
    myClass = Object.prototype.toString.call(obj);
    if (myClass in classToType) {
      return classToType[myClass];
    }
    return "object";
  };

  glocount = 0;

  dummyinspect = function(arg1) {
    return arg1;
  };

  genericinspect = dummyinspect;

  colors = require('enkicolor');

  if (isnode) {
    fs = require('fs');
    util = require('util');
    genericinspect = function(arg) {
      return util.inspect(arg, false, 6, true);
    };
    decklog = fs.createWriteStream('logs/deck.log');
    clientlog = fs.createWriteStream('logs/client.log');
    serverlog = fs.createWriteStream('logs/server.log');
    otherlog = fs.createWriteStream('logs/other.log');
    _ref = [decklog, clientlog, serverlog];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      lfile = _ref[_i];
      for (abc = _j = 1; _j <= 10; abc = ++_j) {
        lfile.write(colors['red']('**********************************************************************\n'));
      }
    }
  } else {
    decklog = null;
    clientlog = null;
    serverlog = null;
  }

  defaults = {
    delimiter: '-',
    delimiterColor: 'green',
    levels: {
      trace: 'grey',
      debug: 'cyan',
      info: 'green',
      warn: 'yellow',
      error: 'red',
      line: 'bold',
      zalgo: 'magenta'
    },
    prefixCol: 'blue',
    dateCol: 'grey',
    suppress: {
      TRACE: false,
      DEBUG: false
    },
    suppress_start: {
      TRACE: [],
      DEBUG: []
    },
    LOGCHANNELS: {
      'default': ['console', decklog],
      'server': ['console', serverlog],
      'client': ['console', clientlog]
    },
    logchan: 'default'
  };

  obj_for_display = function(obj, context, myinspect) {
    var elem, i, key, processq, tmpcnt, typ, val, _k, _len1;
    context = context || {};
    if (!(context.final != null)) {
      context.final = true;
    }
    if (!isnode) {
      return obj;
    }
    context.seenbook = context.seenbook || [];
    typ = type_to_string(obj);
    processq = null;
    if (typ === 'object' || typ === 'function') {
      if (obj instanceof Error) {
        return obj;
      }
      if (__indexOf.call(context.seenbook, obj) >= 0) {
        return '<CIRCULAR>';
      }
      context.seenbook.push(obj);
      if (obj._refid) {
        typ = 'ref';
        processq = '<REF ' + obj.get_refpath().join('/') + '>';
      } else {
        processq = {};
        tmpcnt = 0;
        for (key in obj) {
          val = obj[key];
          tmpcnt += 1;
          if (!(context.skipunderscore && key.indexOf('_') === 0)) {
            processq[key] = obj_for_display(val, merge(context, {
              final: false
            }), myinspect);
          }
        }
        if (tmpcnt === 0) {
          processq = obj;
        }
      }
    } else if (typ === 'array') {
      processq = [];
      for (i = _k = 0, _len1 = obj.length; _k < _len1; i = ++_k) {
        elem = obj[i];
        processq.push(obj_for_display(elem, merge(context, {
          final: false
        }), myinspect));
      }
    } else if (typ === 'undefined') {
      return void 0;
    } else if (typ === 'null') {
      return null;
    } else {
      return obj;
    }
    if (!context.final) {
      return processq;
    } else {
      return myinspect(processq, false, 6, true);
    }
  };

  StumpLog = (function() {

    function StumpLog(desc_callback, custom, parent, root) {
      var key, val, _ref1;
      this.parent = parent;
      this.root = root;
      this.stumpify = __bind(this.stumpify, this);

      this.suppress = __bind(this.suppress, this);

      this.sub = __bind(this.sub, this);

      this._prep_log_console = __bind(this._prep_log_console, this);

      this._log = __bind(this._log, this);

      this.log = __bind(this.log, this);

      this.root = this.root || this.parent || this;
      custom = custom || {};
      this.config = merge(defaults, custom);
      this.desc_callback = desc_callback || function() {
        return '';
      };
      if (type_to_string(this.desc_callback) !== 'function') {
        this.desc_callback = function() {
          return desc_callback;
        };
      }
      _ref1 = this.config.levels;
      for (key in _ref1) {
        val = _ref1[key];
        this[key] = this._log.bind(this, key);
      }
    }

    StumpLog.prototype.log = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return this.info.apply(this, args);
    };

    StumpLog.prototype._log = function() {
      var args, chan, colorline, colormsg, lchans, level, newstr, nocolors, plainline, x, _k, _len1, _results,
        _this = this;
      level = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      lchans = this.config.LOGCHANNELS[this.config.logchan];
      colormsg = this._prep_log_console.apply(this, [colors, genericinspect, level].concat(__slice.call(args)));
      nocolors = {
        green: function(a) {
          return a;
        },
        grey: function(a) {
          return a;
        },
        blue: function(a) {
          return a;
        },
        bold: function(a) {
          return a;
        },
        red: function(a) {
          return a;
        },
        cyan: function(a) {
          return a;
        }
      };
      glocount += 1;
      _results = [];
      for (_k = 0, _len1 = lchans.length; _k < _len1; _k++) {
        chan = lchans[_k];
        if (!chan) {
          continue;
        }
        if (chan === 'console') {
          _results.push(console.log.apply(console, colormsg));
        } else {
          colorline = colormsg.join(' ') + '\n';
          plainline = colorline.replace(/\u001b\[..?m/g, '');
          newstr = ((function() {
            var _l, _len2, _ref1, _results1;
            _ref1 = plainline.split(/\n/g);
            _results1 = [];
            for (_l = 0, _len2 = _ref1.length; _l < _len2; _l++) {
              x = _ref1[_l];
              _results1.push(x.replace(/./g, ' '));
            }
            return _results1;
          })()).join("\n");
          chan.write(glocount + ' ' + colorline);
          if (chan === serverlog) {
            clientlog.write(glocount + ' ' + newstr);
            _results.push(decklog.write(glocount + ' ' + newstr));
          } else if (chan === clientlog) {
            serverlog.write(glocount + ' ' + newstr);
            _results.push(decklog.write(glocount + ' ' + newstr));
          } else if (chan === decklog) {
            serverlog.write(glocount + ' ' + newstr);
            _results.push(clientlog.write(glocount + ' ' + newstr));
          } else {
            _results.push(void 0);
          }
        }
      }
      return _results;
    };

    StumpLog.prototype._prep_log_console = function() {
      var arg, args, delim, desc, dtmp, elem, level, level_suppress, logmsg, mycolors, myinspect, x, _k, _l, _len1, _len2, _len3, _m, _ref1;
      mycolors = arguments[0], myinspect = arguments[1], level = arguments[2], args = 4 <= arguments.length ? __slice.call(arguments, 3) : [];
      if (this.config.suppress[level.toUpperCase()]) {
        return;
      }
      level_suppress = this.root.config.suppress_start[level.toUpperCase()] || [];
      desc = this.desc_callback();
      for (_k = 0, _len1 = level_suppress.length; _k < _len1; _k++) {
        x = level_suppress[_k];
        if (desc.indexOf(x) >= 0) {
          return;
        }
      }
      delim = mycolors[this.config.delimiterColor](this.config.delimiter);
      dtmp = new Date();
      logmsg = [mycolors[this.config.dateCol](dtmp.toLocaleTimeString() + '.' + dtmp.getMilliseconds()), delim, mycolors[this.config['levels'][level]](level.toUpperCase()), delim];
      _ref1 = this.get_logchain();
      for (_l = 0, _len2 = _ref1.length; _l < _len2; _l++) {
        elem = _ref1[_l];
        logmsg.push(mycolors.bold(mycolors[this.config['prefixCol']](elem)));
        logmsg.push(delim);
      }
      for (_m = 0, _len3 = args.length; _m < _len3; _m++) {
        arg = args[_m];
        if (arg === null) {
          arg = '[null]';
        }
        if (arg === void 0) {
          arg = '[undefined]';
        }
        logmsg.push(mycolors[this.config['levels'][level]](obj_for_display(arg, {}, myinspect)));
      }
      return logmsg;
    };

    StumpLog.prototype.get_logchain = function() {
      var coll, tmp, x;
      x = this;
      coll = [];
      while (x) {
        tmp = (typeof x.desc_callback === "function" ? x.desc_callback() : void 0) || x.desc_callback;
        if (tmp && tmp.length > 0) {
          coll.push(tmp);
        }
        x = x.parent;
      }
      return coll.reverse();
    };

    StumpLog.prototype.sub = function(desc_callback) {
      var sublog;
      sublog = new StumpLog(desc_callback, this.config, this, this.root);
      return sublog;
    };

    StumpLog.prototype.suppress = function(level) {
      return this.config.suppress[level.toUpperCase()] = true;
    };

    StumpLog.prototype.stumpify = function(target, desc_callback) {
      var key, sublog, val, _ref1;
      sublog = this.sub(desc_callback);
      _ref1 = sublog.config.levels;
      for (key in _ref1) {
        val = _ref1[key];
        target[key] = sublog[key];
      }
      target.stumpify = sublog.stumpify;
      target.log = sublog.log;
      return target._stump = sublog;
    };

    return StumpLog;

  })();

  module.exports = new StumpLog();

  module.exports.StumpLog = StumpLog;

  module.exports.obj_for_display = obj_for_display;

}).call(this);
